Ensure backup and restore scripts exit if any commands fail

diff --git a/templates/backup.sh.tmpl b/templates/backup.sh.tmpl
--- a/templates/backup.sh.tmpl
+++ b/templates/backup.sh.tmpl
@@ -1,4 +1,7 @@
 #!/bin/bash
+# exit when any command fails
+set -e
+
 BACKUP_DATE=$(date)
 echo $${BACKUP_DATE} > ~/jellyfin/config/backup.log
 aws s3 sync ~/jellyfin/config "s3://${BUCKET}/$${BACKUP_DATE}" --delete
diff --git a/templates/restore.sh.tmpl b/templates/restore.sh.tmpl
--- a/templates/restore.sh.tmpl
+++ b/templates/restore.sh.tmpl
@@ -1,4 +1,7 @@
 #!/bin/bash
+# exit when any command fails
+set -e
+
 aws s3 sync "s3://${BUCKET}/$1" /tmp/jfconfig --delete
 echo "The config backup you specified was taken on: "
 cat /tmp/jfconfig/backup.log
